[general]
host = "0.0.0.0"
port = 6432

# Fórmula: 2 por núcleo.
workers = 0

default_pool_size = 15    # aumenta para suportar múltiplas conexões
min_pool_size = 5
checkout_timeout = 10000  # 10s para evitar falhas prematuras
healthcheck_interval = 30000
idle_healthcheck_interval = 30000

# Método de balanceamento de carga.
# round_robin: revezamento.
# random: aleatório.
# least_active_connections: prioriza o banco de menor carga.
load_balancing_strategy = "least_active_connections"

[[databases]]
host = "db"
name = "postgres"

[[databases]]
host = "db"
name = "mydb"

[admin]
# Senha do usuário administrativo.
# Ver https://docs.pgdog.dev/administration.
password = "admin"